version: '3.8'

services:
  api:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8003:8003" # Expose le port 8003 pour l'API principale
    depends_on:
      - db # Assure que le service PostgreSQL démarre avant l'application
    environment:
      - DATABASE_URL=postgresql+psycopg://lab2user:password@db/lab2db
    command: uvicorn src.main:app --host 0.0.0.0 --port 8003 --reload

  interface:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8004:8004" # Expose le port 8004 pour l'interface web
    depends_on:
      - db # Assure que le service PostgreSQL démarre avant l'application
    environment:
      - DATABASE_URL=postgresql+psycopg://lab2user:password@db/lab2db
    command: uvicorn src.interface:app --host 0.0.0.0 --port 8004 --reload

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lab2user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab2db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose le port 5432 pour PostgreSQL

volumes:
  postgres_data:
